import type { SourceOverview } from "./types";

export const sourceOverviews: SourceOverview[] = [
  {
    id: "flatex",
    name: "Flatex",
    kind: "broker",
    purpose: "Aktien, ETFs, Cash, Depotentwicklung",
    status: "ready",
    importMethod: "Depotübersicht-Snapshot aus Drive",
    nextStep: "Cash-Abgleich und Kontoauszüge in den Bestand integrieren",
  },
  {
    id: "traderepublic",
    name: "Trade Republic",
    kind: "broker",
    purpose: "Aktien, ETFs, Cash, Zinsen",
    status: "ready",
    importMethod: "Net-Worth-PDF aus Drive",
    nextStep: "TransactionExport fachlich in Transaktionen zerlegen",
  },
  {
    id: "ginmon",
    name: "Ginmon",
    kind: "robo",
    purpose: "Robo-Advisor, Global 8 / AP18",
    status: "automated",
    importMethod: "Vermögensstatus-PDF aus Drive",
    nextStep: "Neuere Reports automatisch erkennen und Kosten extrahieren",
  },
  {
    id: "intergold",
    name: "Intergold",
    kind: "metals",
    purpose: "Edelmetalle und Technologiemetalle",
    status: "automated",
    importMethod: "Einlagerungsbelege plus Intergold-Ankaufspreise",
    nextStep: "Storage aktivieren nach Billing-Entscheidung",
  },
  {
    id: "bitget",
    name: "Bitget",
    kind: "crypto",
    purpose: "BTC und spätere Krypto-Positionen",
    status: "planned",
    importMethod: "Read-only API",
    nextStep: "API-Key später nur lesend hinterlegen",
  },
  {
    id: "capitalcom",
    name: "Capital.com",
    kind: "broker",
    purpose: "CFD / Trading-Konto",
    status: "planned",
    importMethod: "Capital.com API, GET-only Agent",
    nextStep: "API-Key erzeugen und lokal im Schluesselbund hinterlegen",
  },
  {
    id: "vbv",
    name: "VBV Vorsorgekasse",
    kind: "pension",
    purpose: "Betriebliche Vorsorge / Abfertigung neu",
    status: "automated",
    importMethod: "Meine-VBV-Login, quartalsweiser Saldo",
    nextStep: "Quartalswert aus Meine VBV aktualisieren",
  },
];
