import type { SourceOverview } from "./types";

export const sourceOverviews: SourceOverview[] = [
  {
    id: "flatex",
    name: "Flatex",
    kind: "broker",
    purpose: "Aktien, ETFs, Cash, Depotentwicklung",
    status: "automated",
    importMethod: "Flatex Broker-Agent plus Dokumenten-Agent",
    nextStep: "Brokerstand und Dokumentfakten regelmaessig gegen Flatex kontrollieren",
  },
  {
    id: "traderepublic",
    name: "Trade Republic",
    kind: "broker",
    purpose: "Aktien, ETFs, Cash, Zinsen",
    status: "ready",
    importMethod: "Portal-Agent plus manuelle Export-Fallbacks",
    nextStep: "Portal-Downloads und Export-Fallbacks fachlich vollstaendig abgleichen",
  },
  {
    id: "ginmon",
    name: "Ginmon",
    kind: "robo",
    purpose: "Robo-Advisor, Global 8 / AP18",
    status: "automated",
    importMethod: "Vermögensstatus-PDF aus Drive",
    nextStep: "Neuere Reports automatisch erkennen und Kosten extrahieren",
  },
  {
    id: "intergold",
    name: "Intergold",
    kind: "metals",
    purpose: "Edelmetalle und Technologiemetalle",
    status: "automated",
    importMethod: "Einlagerungsbelege plus Intergold-Ankaufspreise",
    nextStep: "Verkaufs-/Rechnungsbelege als Bestandsreduktion ergaenzen",
  },
  {
    id: "bitget",
    name: "Bitget",
    kind: "crypto",
    purpose: "BTC und spätere Krypto-Positionen",
    status: "automated",
    importMethod: "Read-only Bitget API plus Ledger-Agent",
    nextStep: "Historische Vollstaendigkeit bei Bedarf mit Export-Backfill pruefen",
  },
  {
    id: "capitalcom",
    name: "Capital.com",
    kind: "broker",
    purpose: "CFD / Trading-Konto",
    status: "planned",
    importMethod: "Capital.com API, GET-only Agent",
    nextStep: "API-Key erzeugen und lokal im Schluesselbund hinterlegen",
  },
  {
    id: "vbv",
    name: "VBV Vorsorgekasse",
    kind: "pension",
    purpose: "Betriebliche Vorsorge / Abfertigung neu",
    status: "automated",
    importMethod: "Meine-VBV-Login, quartalsweiser Saldo",
    nextStep: "Quartalswert aus Meine VBV aktualisieren",
  },
  {
    id: "equateplus",
    name: "EquatePlus",
    kind: "equity_plan",
    purpose: "Mitarbeiteraktien / Beteiligungsprogramm",
    status: "blocked",
    importMethod: "Zurueckgestellt bis erste Mail-Dokumente eintreffen",
    nextStep: "Erste EquatePlus-Mail analysieren, Dokumenttypen klassifizieren und Parser planen",
  },
  {
    id: "bank_accounts",
    name: "Bankkonten",
    kind: "bank",
    purpose: "Geldstand, Kreditlinien, Transaktionen",
    status: "automated",
    importMethod: "Read-only Open Banking ueber Enable Banking",
    nextStep: "Umsaetze je Konto als ledgerEntries anzeigen und Kosten/Zinsen klassifizieren",
  },
];
